#!/bin/sh
set -e

case "$1" in
    configure)
        # Create symbolic link for easy access
        ln -sf /usr/share/ros-hacks/setup.sh /usr/bin/ros-hacks-setup
        
        echo "ROS-Hacks has been installed! Running setup..."
        /usr/bin/ros-hacks-setup
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
