#!/bin/sh
set -e

# Automatically added by debhelper
#DEBHELPER#

case "$1" in
    configure)
        # Create symbolic link for easy access
        ln -sf /usr/share/ros-hacks/install/setup.sh /usr/bin/ros-hacks-setup
        ln -sf /usr/share/ros-hacks/bin/ros-hacks.sh /usr/bin/ros-hacks
        
        echo "ROS-Hacks has been installed!"
        if [ -z "$CI" ]; then
            echo "Running setup..."
            # Make sure the script is executable
            chmod +x /usr/share/ros-hacks/install/setup.sh
            /usr/share/ros-hacks/install/setup.sh
        else
            echo "Skipping setup in CI environment."
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
