#!/bin/sh
set -e

case "$1" in
    configure)
        echo "Creating symbolic link: /usr/bin/ros-hacks-setup -> /usr/share/ros-hacks/setup.sh"
        ln -sf /usr/share/ros-hacks/setup.sh /usr/bin/ros-hacks-setup
        ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
        # No special action needed
        ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
