#!/bin/sh
set -e

# Automatically added by debhelper
#DEBHELPER#

case "$1" in
    configure)
        # Create symbolic link for easy access
        ln -sf /usr/share/ros-hacks/setup.sh /usr/bin/ros-hacks-setup
        
        echo "ROS-Hacks has been installed!"
        if [ -z "$CI" ]; then
            echo "Running setup..."
            /usr/bin/ros-hacks-setup
        else
            echo "Skipping setup in CI environment."
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
